apiVersion: apps/v1
kind: Deployment
metadata:
  name: wowhoneypot
  namespace: wowhoneypot
  labels:
    app: wowhoneypot
    type: honeypot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wowhoneypot
  template:
    metadata:
      labels:
        app: wowhoneypot
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
        - name: wowhoneypot
          image: ryusa/wowhoneypot:1.0
          securityContext:
            capabilities:
              drop:
                - ALL
              add:
                - CAP_NET_BIND_SERVICE
          env:
            - name: TLS_ENABLE
              value: "True"
            - name: CERTFILE_PATH
              value: "/app/cert/server.pem"
            - name: "PORT"
              value: "8080"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: wowhoneypot-cert
              mountPath: /app/cert
              readOnly: true
      volumes:
        - name: wowhoneypot-cert
          secret:
            secretName: wowhoneypot-cert
