apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fluentd-wowhoneypot
rules:
  - apiGroups: [""]
    resources:
      - namespaces
      - pods
      - pods/logs
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fluentd-wowhoneypot-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fluentd-fluentd-wowhoneypot
subjects:
  - kind: ServiceAccount
    name: fluentd-wowhoneypot-sa
    namespace: wowhoneypot
